config/routes.rb
Rails.application.routes.draw do
  root 'joints#index'
  resources :joints
  resources :parts
  resources :tags
  resources :joint_parts
  resources :joint_tags
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  direct :github do
    'https://github.com/tsukalab/jointhub'
  end
  get '/download/:id', to: 'joints#download_parts_file', as: 'download_zip'
end

app/models/part.rb
# == Schema Information
#
# Table name: parts
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  stl        :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Part < ApplicationRecord
  mount_uploader :stl, StlUploader
  has_many :joint_parts, dependent: :destroy
  has_many :joints, through: :joint_parts
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[show edit update destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all.page(params[:page])
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, success: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, success: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, success: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_part
    @part = Part.find(params[:id])
  end

  def part_params
    params.require(:part).permit(:name, :stl, :stl_cache)
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for(part) do |f| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="file-field input-field">
    <div class="btn">
      <span>FILE</span>
      <%= f.file_field :stl %>
      <%= f.hidden_field :stl_cache %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Upload your stl file">
    </div>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="commit">Submit
    <i class="material-icons right">send</i>
  </button>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.name %></td>
        <td><%= link_to 'Download', part.stl.url %></td>
        <td><%= link_to 'Show', part %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_part_path(part) %></td>
          <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @parts %>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>
<br>
<%= link_to 'Back', parts_path, class: 'btn' %>

app/views/parts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @part.name %>
</p>

<%= react_component('MyStlView',
  { url: @part.stl.url, width: 400, height: 400, rotate: true, orbitControls: true }) %>

<p><%= link_to 'Download link', @part.stl.url %></p>

<br>
<%= link_to 'Back', parts_path, class: "btn"%>
<% if user_signed_in? %>
<%= link_to edit_part_path(@part), class: "btn" do %>
  <i class="material-icons">mode_edit</i>
<% end %>
<% end %>