config/routes.rb
Rails.application.routes.draw do
  root 'joints#index'
  resources :joints
  resources :parts
  resources :tags
  resources :joint_parts
  resources :joint_tags
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  direct :github do
    'https://github.com/tsukalab/jointhub'
  end
  get '/download/:id', to: 'joints#download_parts_file', as: 'download_zip'
end

app/models/joint.rb
# == Schema Information
#
# Table name: joints
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  description :text
#  image       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Joint < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :joint_parts, dependent: :destroy
  has_many :joint_tags, dependent: :destroy
  has_many :parts, through: :joint_parts
  has_many :tags, through: :joint_tags

  def self.search(search)
    if search
      Joint.where(['name LIKE ?', "%#{search}%"])
    else
      Joint.all
    end
  end
end

app/controllers/joints_controller.rb
class JointsController < ApplicationController
  include Zipline
  before_action :authenticate_user!, only: %i[edit update destroy]
  before_action :set_joint, only: %i[show edit update destroy download_parts_file]

  # GET /joints
  # GET /joints.json
  def index
    if params[:tag_id].nil?
      @joints = Joint.search(params[:search]).page(params[:page])
    else
      @joints = Tag.find(params[:tag_id]).joints.page(params[:page])
    end
  end

  # GET /joints/1
  # GET /joints/1.json
  def show
  end

  # GET /joints/new
  def new
    @joint = Joint.new
  end

  # GET /joints/1/edit
  def edit
  end

  # POST /joints
  # POST /joints.json
  def create
    @joint = Joint.new(joint_params)

    respond_to do |format|
      if @joint.save
        format.html { redirect_to @joint, flash: { success: 'Joint was successfully created.' } }
        format.json { render :show, status: :created, location: @joint }
      else
        format.html { render :new }
        format.json { render json: @joint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joints/1
  # PATCH/PUT /joints/1.json
  def update
    respond_to do |format|
      if @joint.update(joint_params)
        format.html { redirect_to @joint, success: 'Joint was successfully updated.' }
        format.json { render :show, status: :ok, location: @joint }
      else
        format.html { render :edit }
        format.json { render json: @joint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joints/1
  # DELETE /joints/1.json
  def destroy
    @joint.destroy
    respond_to do |format|
      format.html { redirect_to joints_url, flash: { success: 'Joint was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  def download_parts_file
    files =  @joint.parts.map{ |part| [part.stl, "#{part.stl_identifier}"] }
    zipline(files, "#{@joint.name}.zip")
  end

  private

  def set_joint
    @joint = Joint.find(params[:id])
  end

  def joint_params
    params.require(:joint).permit(
      :name, :description, :image, :image_cache, part_ids: [], tag_ids: []
    )
  end
end

app/helpers/joints_helper.rb
module JointsHelper
end

app/views/joints/_form.html.erb
<%= form_for(joint) do |f| %>
  <% if joint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joint.errors.count, "error") %> prohibited this joint from being saved:</h2>

      <ul>
      <% joint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="file-field input-field">
    <div class="btn">
      <span>FILE</span>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Upload your thumbnail file">
    </div>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="commit">Save
    <i class="material-icons right">done</i>
  </button>
<% end %>

app/views/joints/edit.html.erb
<h1>Editing Joint</h1>

<%= form_for(@joint) do |f| %>
  <% if @joint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joint.errors.count, "error") %> prohibited this joint from being saved:</h2>

      <ul>
      <% @joint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <label>Description</label>
  <div class="input-field">
    <%= f.text_area :description, class: "materialize-textarea"%>
  </div>

  <label>Tag</label>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |b| %>
    <p>
      <%= b.check_box %>
      <%= b.label %>
    </p>
  <% end %>

  <label>使用パーツ</label>
  <%= f.collection_check_boxes(:part_ids, Part.all, :id, :name) do |b| %>
    <p>
      <%= b.check_box %>
      <%= b.label %>
    </p>
  <% end %>

  <div class="file-field input-field">
    <div class="btn">
      <span>FILE</span>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Upload your thumbnail file">
    </div>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="commit">Save
    <i class="material-icons right">done</i>
  </button>
<% end %>

<br>

<%= link_to 'Show', @joint, class: "btn" %>
<%= link_to 'Back', joints_path, class: "btn" %>

app/views/joints/index.html.erb
<% @joints.each do |joint| %>
  <div class="col s4">
    <div class="card hoverable">
      <div class="card-image">
        <%= image_tag joint.image, class: "index-image" %>
        <% if user_signed_in? %>
        <div class="card-image-btn fixed-action-btn horizontal">
          <a class="btn-floating btn-large"><i class="large material-icons">menu</i></a>
          <ul>
            <li>
              <%= link_to joint_path(joint), class: "btn-floating blue" do %>
                <i class="material-icons">zoom_in</i></a>
              <% end %>
            </li>
            <li>
              <%= link_to edit_joint_path(joint), class: "btn-floating yellow darken-1" do %>
                <i class="material-icons">mode_edit</i>
              <% end %>
            </li>
            <li>
              <%= link_to joint_path(joint), method: :delete, class: "btn-floating red", data: { confirm: 'Are you sure?' } do %>
                <i class="material-icons">delete</i>
              <% end %>
            </li>
          </ul>
        </div>
        <% else %>
        <div class="card-image-btn fixed-action-btn horizontal">
          <%= link_to joint_path(joint), class: "btn-floating btn-large" do %>
            <i class="material-icons">zoom_in</i></a>
          <% end %>
        </div>
        <% end %>
      </div>
      <div class="card-content card-content-index">
        <span class="card-title grey-text text-darken-4"><%= joint.name %></span>
        <% joint.tags.each do |tag| %>
          <div class="chip">
            <%= link_to tag.name, tag_path(tag)%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @joints %>

app/views/joints/new.html.erb
<h1>New Joint</h1>

<%= render 'form', joint: @joint %>
<br>
<%= link_to 'Back', joints_path, class: "btn"%>

app/views/joints/show.html.erb
<div class="card horizontal">
  <div class="card-image">
    <%= image_tag @joint.image %>
  </div>
  <div class="card-stacked">
    <div class="card-content">
      <span class="card-title"><%= @joint.name %></span>
      <p><%= @joint.description %></p>
      <br>
      Tag: <% @joint.tags.each do |tag| %>
        <div class="chip">
          <%= link_to tag.name, tag_path(tag)%>
        </div>
      <% end %>
      <br>
      Part: <% @joint.parts.each do |part| %>
        <div class="chip">
          <%= link_to part.name, part_path(part) %>
        </div>
      <% end %>
    </div>
    <div class="card-action">
      <%= link_to 'Download ZIP', download_zip_path(@joint) %>
      <% if user_signed_in? %>
        <%= link_to 'Edit Joint', edit_joint_path(@joint) %>
      <% end %>
    </div>
  </div>
</div>