config/routes.rb
Rails.application.routes.draw do
  root 'joints#index'
  resources :joints
  resources :parts
  resources :tags
  resources :joint_parts
  resources :joint_tags
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  direct :github do
    'https://github.com/tsukalab/jointhub'
  end
  get '/download/:id', to: 'joints#download_parts_file', as: 'download_zip'
end

app/views/layouts/_header.html.erb
<nav class="nav-extended">
  <div class='nav-wrapper'>
    <%= link_to 'JointSystem', root_path, class: 'brand-logo center' %>
    <ul id='nav-mobile' class='left hide-on-med-and-down'>
      <li><%= link_to 'Joint', joints_path %></li>
      <li><%= link_to 'Part', parts_path %></li>
      <li><%= link_to 'Tag', tags_path %></li>
    </ul>
    <ul id='nav-mobile' class='right hide-on-med-and-down'>
      <li>
          <%= form_with(url: joints_path, method: 'get') do |f| %>
            <div class='input-field'>
              <%= f.text_field :search, class: 'validate', id: 'icon_prefix', type: 'search', required: '' %>
              <%= f.label :search, class: 'label-icon' do %>
                <i class="material-icons">search</i>
              <% end %>
              <i class="material-icons">close</i>
            </div>
          <% end %>
      </li>
      <li><%= link_to 'GitHub', github_url %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li><%= link_to 'Login with Facebook', user_facebook_omniauth_authorize_path %></li>
      <% end %>
    </ul>
  </div>
  <% if user_signed_in? %>
    <div class="nav-content add-content-btn">
      <% if current_page?(joints_path) or current_page?(root_path) %>
        <%= link_to new_joint_path, class: "btn-floating btn-large waves-effect waves-light halfway-fab" do %>
          <i class="material-icons">add</i>
        <% end %>
      <% end %>
      <% if current_page?(parts_path) %>
        <%= link_to new_part_path, class: "btn-floating btn-large waves-effect waves-light halfway-fab" do %>
          <i class="material-icons">add</i>
        <% end %>
      <% end %>
      <% if current_page?(tags_path) %>
        <%= link_to new_tag_path, class: "btn-floating btn-large waves-effect waves-light halfway-fab" do %>
          <i class="material-icons">add</i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>jointhub</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |type, message| %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, '#{type}')" %>
      <% end %>
      <div class="row card-panel">
        <%= yield %>
      </div>
    </div>
  </body>
</html>